[tool.poetry]
name = "fast-qaoa"
version = "0.1.2"
description = ""
authors = ["David Bucher <d.bucher97@gmail.com>"]
readme = "README.md"
build = 'build.py'
packages = [{include = "fastqaoa"}]
include = [
    {path = "fastqaoa/ctypes/*.dylib"},
    {path = "fastqaoa/ctypes/*.so"}
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
ipython = "^8.16.1"
qubovert = "^1.2.5"
jupyterlab = "^4.0.7"
matplotlib = "^3.8.0"
seaborn = "^0.13.0"
pyarrow = "^14.0.0"
scikit-learn = "^1.3.2"
statsmodels = "^0.14.1"
tqdm = "^4.66.1"
h5py = "^3.10.0"
pydantic = "^2.4.2"
importlib-resources = "^6.1.0"
toml = "^0.10.2"
jax = {version = "0.4.17", extras = ["cpu"]}
pennylane = "^0.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
