[tool.poetry]
name = "fast-qaoa"
version = "0.1.0"
description = ""
authors = ["David Bucher <d.bucher97@gmail.com>"]
readme = "README.md"
packages = [{include = "fastqaoa"}, {include = "problems"}]

[tool.poetry.dependencies]
python = "^3.11"
networkx = "^3.2"
qubovert = "^1.2.5"
jax = {version = "0.4.17", extras = ["cpu"]}
matplotlib = "^3.8.0"
seaborn = "^0.13.0"
pennylane = "^0.32.0"
pyarrow = "^14.0.0"
ipython = "^8.17.2"
toml = "^0.10.2"
pydantic = "^2.4.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
ipython = "^8.16.1"
jupyterlab = "^4.0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
